import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/shared/Navbar";
import { Footer } from "@/Components/footer/Footer";
import ContextApi from "@/context/ContextApi";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={` h-full `}
    >
      
      <body className="min-h-full flex flex-col">
        <ContextApi>
        <Navbar/>
        {children}
         <Footer/>
        </ContextApi>
        </body>
    </html>
  );
}
